#!/bin/bash

if [ "$XDG_SESSION_TYPE" = "x11" ]; then
    if [ -f /tmp/deepin_update_option.json ]; then
        systemctl --user start dde-update-env.service
        /usr/bin/dde-update
        systemctl --user stop dde-update-env.service
    fi
elif [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    if [ -f /tmp/deepin_update_option.json ]; then
        /usr/bin/run-kwayland-check-wrapper.sh
    fi
fi
